[package]
name = "spvc"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
error-chain = "0.11"
rspirv = "0.4"
spirv_headers = "1.1"
glsl-struct = { path = "./glsl-struct", version = "0.1" }
glsl-struct-derive = { path = "./glsl-struct-derive", version = "0.1" }
