[package]
name = "spvc-shader"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[features]
default = ["vulkan"]
vulkan = ["vulkano"]

[dependencies]
error-chain = "0.11"
rspirv = "0.4"
spirv_headers = "1.1"

[dependencies.vulkano]
version = "0.6"
optional = true
